#!/bin/bash

## Copyright (C) 2025 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -o errexit
set -o nounset
set -o errtrace
set -o pipefail

autopkgtest_tarball_path="$HOME/.cache/sbuild/bookworm-amd64.tar.zst"
privleap_project_dir="$(dirname "$(readlink -f "${0}")")"
target_distribution="bookworm"

create_autopkgtest_tarball() {
  mkdir -p ~/.cache/sbuild
  sudo mmdebstrap \
    --include=ca-certificates \
    --skip=output/dev \
    --variant=buildd \
    "${target_distribution}" \
    "${HOME}/.cache/sbuild/${target_distribution}-amd64.tar.zst" \
    --customize-hook='chroot "$1" passwd --delete root' \
    --customize-hook='chroot "$1" useradd --home-dir /home/user --create-home user' \
    --customize-hook='chroot "$1" passwd --delete user' \
    --customize-hook='cp /etc/hosts "$1/etc/hosts"' \
    --customize-hook=/usr/share/autopkgtest/setup-commands/setup-testbed \
    https://deb.debian.org/debian
}

run_autopkgtest() {
  ## Ensure unshare executable exists, it's critical for this script to work
  if ! [ -x '/usr/bin/unshare' ]; then
    1>&2 echo 'Cannot find unshare executable!'
    exit 1
  fi
  if [ "$(basename "${privleap_project_dir}")" != 'privleap' ]; then
    1>&2 echo 'The run_autopkgtest script does not appear to be in the root of the privleap source tree!'
    exit 1
  fi
  if [ "$(stat -c "%u|%a" /usr/bin/newuidmap)" != '0|4755' ]; then
    1>&2 echo 'autopkgtest requires /usr/bin/newuidmap to be SUID-root!'
    exit 1
  fi
  if [ "$(stat -c "%u|%a" /usr/bin/newgidmap)" != '0|4755' ]; then
    1>&2 echo 'autopkgtest requires /usr/bin/newgidmap to be SUID-root!'
    exit 1
  fi
  if [ "$(pwd)" != "${privleap_project_dir}" ]; then
    cd "${privleap_project_dir}" >/dev/null || {
      1>&2 echo 'Cannot change to privleap source tree directory!'
      exit 1
    }
  fi

  if ! [ -f "${autopkgtest_tarball_path}" ]; then
    create_autopkgtest_tarball
  fi

  dpkg-buildpackage -i -us -uc -b || {
    1>&2 echo 'Cannot build privleap deb package!'
    exit 1
  }
  cd ..
  autopkgtest -l "${privleap_project_dir}/privleap-test-log.txt" \
    --apt-upgrade -B privleap*.deb "${privleap_project_dir}" -- unshare
  echo "Test complete. Results are stored in ${privleap_project_dir}/privleap-test-log.txt."
}

run_autopkgtest
